### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by brajesheee** [ironmussa/Optimus#1011]
**Describe the bug**
I am unable to install the optimuspyspark using pip for version 2.2.29

**To Reproduce**
pip install error with  message " No such file or directory requirement.txt"

**Expected behavior**
pip install should not fail

**Comment by argenisleon** [comment]
Hi @brajesheee,
Checking this, I'll be back ASAP

**Comment by argenisleon** [comment]
@brajesheee I released version 2.2.32. Please let me know if everything is working.

**Comment by brajesheee** [comment]
@argenisleon i see the only version upto 2.2.29 in pypi when i use pip command in python 3.7 version

**Comment by argenisleon** [comment]
Seems weird can you check use

`pip install optimuspyspark==` and see what happens. I get something,
![image](https://user-images.githubusercontent.com/37144/87881906-203e1780-c9c2-11ea-921b-36993939adab.png)

Can you verify that version 2.2.32 is available on your side?

**Comment by brajesheee** [comment]
Found why it is happening, I see issue since we using nexus repo proxy. Outside it, it is working fine for the latest version. But still the old version have same problem. Can we fix the same in old versions too ?

**Comment by argenisleon** [comment]
Hi @brajesheee,
As fas, as I know, is not possible to replace and already published version in PyPI. Just curious, Why can not you use the lastest version?

**Comment by argenisleon** [comment]
@brajesheee I can reopen this if want to keep this conversation
