### ISSUE TITLE
Too much logs printed. It's at least 10x slower.

### ISSUE THREAD

**Issue by Pcosmin** [ironmussa/Optimus#1063]
Version: 2.2.32
The profiling process print a lot of useless logs which makes the process very slow. I think you should remove the print from optimus/infer.py:309, where it prints the dtypes: 
"print(dtypes)"

With "print(dtypes)" it took a very long time, I waited for over 10 minutes to print all the dtypes, and it didn't finish to print all of them. After 10 minutes I just killed the process.
Without "print(dtypes)" it took 96 seconds for the whole profiling process to be done.

**Comment by argenisleon** [comment]
Thanks for the report @Pcosmin. Could you send  PR?

**Comment by Pcosmin** [comment]
Hi @argenisleon . I sent the PR: https://github.com/ironmussa/Optimus/pull/1064 . Please let me know if there are other changes that I should do.

**Comment by argenisleon** [comment]
Thanks @Pcosmin. Merged
