### ISSUE TITLE
Incompatibility with recent versions of pandas

### ISSUE THREAD

**Issue by dersteppenwolf** [ironmussa/Optimus#1067]
Looks like optimus has some kind of incompatibilities with recent versions of pandas

**To Reproduce**

```python
from pyspark.sql import SparkSession
from optimus import Optimus

spark = SparkSession.builder.appName('optimus').getOrCreate()
op= Optimus(spark)

odf = op.load.parquet("/myfolder/myfile.parquet")
```

error:
_/databricks/driver
ImportError: cannot import name 'PY2' from 'pandas.compat' (/databricks/python/lib/python3.7/site-packages/pandas/compat/__init__.py)_

**Cluster environment:**
 - Databricks Apache Spark 3.0.0, Scala 2.12)
- Pandas v 1.1.4

**Comment by argenisleon** [comment]
Hi @dersteppenwolf.

The `load.parquet` method is just syntactic sugar over the original pyspark method. 
Could you check what happens when trying to load the parquet file with vanilla pyspark?

**Comment by argenisleon** [comment]
@dersteppenwolf Let me know if you need any other issue
