### ISSUE TITLE
Wrapping o modifying the transformer.get_data_frame().show() function

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#109]
@FavioVazquez 
If we want to abstract the use of the spark dataframe structure, I think we should consider use something like:

transformer.show() 
instead of  
transformer.get_data_frame().show()

Is shorter, easier to use and you do not need to deal with df

**Comment by FavioVazquez** [comment]
It is true, it will be a fix for the 1.0.1 version

**Comment by FavioVazquez** [comment]
Closed by #111
