### ISSUE TITLE
Sampling and processing the whole data set

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#110]
@FavioVazquez 
I think should be an easy way to take a data sample, make all the operations and then apply them to the whole dataset. In this way, if we have a data set of 5TB we do not need to process the all the data that could be time-consuming.

For example:

Sample Dataset
```
transformer.sample().trim_col("*") 
           .remove_special_chars("*") 
           .clear_accents("*") 
           .lower_case("*") 
```
Whole dataset
```
transformer.trim_col("*") 
           .remove_special_chars("*") 
           .clear_accents("*") 
           .lower_case("*") 
```

This approach should be the easiest to implement but there are have some problems here. The user has to copy paste the whole chaining and apply it to the whole dataset. Another approach could be something like that(not python):

```
operations = [trim_col("*"), remove_special_chars("*"),  clear_accents("*"), lower_case("*") ]
#Transformation in the sample dataset
transfomer.sample().apply(operations)
#Transformation in the whole dataset
transfomer.apply(operations)
```

## The problem with a random sample

We talk about the possibility to use a random sample function from Spark. Although this could be the first approach I think there are 2 problems we have to tackle.

**Empty data**

The trainers do not accept empty data. If we can not detect empty data on the sample and we do not remove it in the whole data set the user could have problems at training time.

**Outliers**

If we can not detect and an outlier in the sample and we do not remove it the whole data set it could generate a flawed model.

We must be sure that our sample data set to meet this requirement. 

## What can we do

I think we must find the fastest way to detect empty data and outliers in the sample function. and be sure that the user has the more accurate representation of the whole data.

**Comment by FavioVazquez** [comment]
Even though this is a great idea there are some problems with sampling data and this is not encouraged. See http://sampleclean.org/activeclean.pdf. Closed as WontFix.

**Comment by argenisleon** [comment]
For clarification after our talk:
The problem in working with samples is when you try for example to detect outliers or impute data and then apply this to the whole dataset.  Of course, this can introduce bias on the trained model.

This method can be applied if you only want to make data wrangling operations like trim, remove special characters, etc
