### ISSUE TITLE
Can't install Optimus on Notebook

### ISSUE THREAD

**Issue by Fluffms** [ironmussa/Optimus#1112]
**Describe the bug**
I'm using Jupyter notebook and I can not install optimuspyspark using 
`!pip install optimuspyspark`

**To Reproduce**
1. I made a new Jupyter notebook ipynb
2. I ran !pip install optimuspyspark as described in the documentation
3.  I ran into the following error:

```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from optimuspyspark) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.5.0rc0, 2.5.0rc1)
ERROR: No matching distribution found for tensorflow==1.13.1 (from optimuspyspark)

```
**Expected behavior**
Succesful install

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Firefox
 - Using Anaconda
 - Notebook version: 6.0.3

**Comment by argenisleon** [comment]
Hi @Fluffms,

Thanks for the report.

It seems that tensorflow==1.13.1 is not available anymore.

I am going to bump the TensorFlow version a release a new Optimus version.

I will available at the end of the day.

**Comment by Fluffms** [comment]
Thank you for your quick reply! I look forward to the changes

**Comment by argenisleon** [comment]
Tensorflow was removed in the last version
