### ISSUE TITLE
ModuleNotFoundError: No module named 'fastnumbers'       

### ISSUE THREAD

**Issue by hello-lei** [ironmussa/Optimus#1119]
type   from optimus import Optimus 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-22e51d4255ae> in <module>
----> 1 from optimus import Optimus

C:\ProgramData\Anaconda3\lib\site-packages\optimus\__init__.py in <module>
      1 # pyspark_pipes: build Spark ML pipelines easily
      2 from .ml.pipelines import patch
----> 3 from .optimus import *
      4 
      5 patch()

C:\ProgramData\Anaconda3\lib\site-packages\optimus\optimus.py in <module>
      3 
      4 from optimus.create import Create
----> 5 from optimus.functions import concat
      6 from optimus.helpers.constants import *
      7 from optimus.helpers.raiseit import RaiseIfNot

C:\ProgramData\Anaconda3\lib\site-packages\optimus\functions.py in <module>
      1 import base64
      2 import logging
----> 3 from fastnumbers import isint, isfloat
      4 from functools import reduce
      5 from io import BytesIO

ModuleNotFoundError: No module named 'fastnumbers'

**Comment by argenisleon** [comment]
Hi @hello-lei ,
Could you check please that Optimus was installed correctly?
Also, could you try to install fast numbers directly?
`pip install fastnumbers`

**Comment by hello-lei** [comment]
ok，I will try，thank you

**Comment by hello-lei** [comment]
Thank for you very much !
pip install fastnumbers,this is valid.
