### ISSUE TITLE
Document missing functions from Read the Docs

### ISSUE THREAD

**Issue by hugounavez** [ironmussa/Optimus#112]

**Comment by KirkHadley** [comment]
#### Missing functions

1. lower_case
2. upper_case
3. impute_missing
4. check_point
5. remove_special_chars_regex
6. cast_func
7. empty_str_to_str
8. row_filter_by_type
9. undo_vec_assembler
10. scale_vec_col
11. split_str_col
12. remove_duplicates

**Comment by FavioVazquez** [comment]
Thanks @KirkHadley! Will add them ASAP.

**Comment by FavioVazquez** [comment]
If you can, you can create a PR with some doc for the functions, and I'll help you there @KirkHadley

**Comment by KirkHadley** [comment]
Don't worry about adding them- I was mostly making that list for my own purposes. You keep on actual code stuff, I'll handle this. Plus writing docs will get me to learn the way around.

**Comment by FavioVazquez** [comment]
Great! Thanks :)
