### ISSUE TITLE
AttributeError: module 'optimus' has no attribute 'Utilities'

### ISSUE THREAD

**Issue by Prajaktaparkhade82** [ironmussa/Optimus#1120]
import optimus as op
tools=op.Utilities()
this.dataframe=tool.read_csv(path=fileName,sep=',')

**Comment by argenisleon** [comment]
Hi @Prajaktaparkhade82,

Sorry for the late response.
This code works in the 1.x version of Optimus. Maybe you take it from the updates docs.
Please check the examples for better docs and how-to's.

https://github.com/hi-primus/optimus/tree/develop-21.9/examples
