### ISSUE TITLE
url_parser  bug in requirements.txt

### ISSUE THREAD

**Issue by liRONCO11** [ironmussa/Optimus#1136]
all version of optimus using git+https://github.com/hi-primus/url_parser@master
but url_parser doesn't have a master branch.
this is a link to the file: https://github.com/hi-primus/optimus/blob/develop-21.8/requirements.txt
please fix to main.
pr: https://github.com/hi-primus/optimus/pull/1137/files
easy fix.

**Comment by avishai-o** [comment]
it's true.
if you can merge the PR.
good work @liRONCO11.

**Comment by luis11011** [comment]
Thank you @liRONCO11 and @avishai-o
