### ISSUE TITLE
DataFrameTransformer.explode_table  example is outdated

### ISSUE THREAD

**Issue by manuzhang** [ironmussa/Optimus#123]
Following the `explode_table` example on doc will return `missing 1 required positional argument: 'list_to_assign'` error

```python
# Instanciation of DataTransformer class:
transformer = op.DataFrameTransformer(df)

# Printing of original dataFrame:
print('Original dataFrame:')
transformer.show()

# Transformation:
transformer.explode_table('bill id', 'foods', 'Beer')

# Printing new dataFrame:
print('New dataFrame:')
transformer.show()
```

**Comment by FavioVazquez** [comment]
Hi @manuzhang thanks for noticing this. This was a bigger problem that we thought but we fix it and think that now it makes more sense what this functions does.

The new example is at:

https://github.com/ironmussa/Optimus/blob/master/docs/index.rst#dataframetransformercount_itemscol_id-col_search-new_col_feature-search_string

Thanks again!

**Comment by manuzhang** [comment]
Thanks. The name makes more sense now since `explode` has a different meaning in Spark.
