### ISSUE TITLE
Creating new instances forces to download nltk data

### ISSUE THREAD

**Issue by israelvainberg** [ironmussa/Optimus#1251]
**Description of the bug**
When creating instances of optimus engine, the main function optimus.Optimus is using nltk to download stopwords, lemmatizer and POS tagger. The download is made using nltk.downloader with the default parameter halt_on_error=True.
When running the package in closed environments (e.g, on private subnets) the download is being blocked which causes the whole process to stuck.

**To Reproduce**
```
from optimus import Optimus
op = Optimus("pandas")
```

**Expected behavior**
Add an optional boolean parameter which indicates optimus to load nltk data when creating a storage engine instance (default False).
For example:
```
op = Optimus("pandas", load_nltk_data=True)
```

**Desktop OS:**
 - OS: Windows 10 & Ubuntu 20.04 TLS

**Additional context**
As a workaround I am using the preferred engine directly by importing it from optimus.
For example:
```
from optimus.optimus import start_pandas
op = start_pandas()
```

**Comment by argenisleon** [comment]
Hi @israelvainberg,

I am going to add this param in the next few days.

Thanks
