### ISSUE TITLE
Error when trying to install Optimus

### ISSUE THREAD

**Issue by atanasj** [ironmussa/Optimus#202]
Hi. I am tying to install via pip, and I'm getting the following error:

            RuntimeError: This version requires Python 3.5+
            
            ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in 
       /private/var/folders/rc/b858tz910wsgc1nm96gxzk9c0000gn/T/pip-build-nM3w8Q/optimuspyspark/

However, I think I have the required python version (3.5.4). I've also tried to install with 'sudo', and still no joy.

Am I doing something wrong? Please help. See the screenshot for more info.

Thanks,
Atanas.

![image](https://user-images.githubusercontent.com/27214625/33938090-37648ff6-e05a-11e7-877e-36473a616575.png)

**Comment by FavioVazquez** [comment]
Hi @atanasj, can you please check your python version? I also think we need python 3.6+ now, but first lets try this

**Comment by FavioVazquez** [comment]
Next version should fix this problem @atanasj. It uses Python 3.6

**Comment by atanasj** [comment]
Hi. Thanks for that. Yep, issue resolved. Thanks.
