### ISSUE TITLE
Does this package work on a 2 node spark cluster or only if its a single node?

### ISSUE THREAD

**Issue by Sarickshah** [ironmussa/Optimus#216]

**Comment by FavioVazquez** [comment]
It works for both single node and cluster mode @Sarickshah

**Comment by Sarickshah** [comment]
Thanks!

**Comment by Sarickshah** [comment]
Hi all, I forgot to ask a followup, do I just install it on the master node and it'll work? or do I need to install on each node or yeah how exactly should I set it up then?

**Comment by FavioVazquez** [comment]
Hi @Sarickshah ! You need a valid spark installation in your nodes. I suggest that if you are in a cluster, install spark from the main webpage, and go from there :)
