### ISSUE TITLE
Allow the output of profiler to be output as text rather than html

### ISSUE THREAD

**Issue by Sarickshah** [ironmussa/Optimus#229]
Can't interact with anything in my environment (open the  toggle details)

**Comment by FavioVazquez** [comment]
Can you send a screenshot please? @Sarickshah

**Comment by Sarickshah** [comment]
[Screenshot](https://lh3.googleusercontent.com/sLqakT7fIFEHFFSOSGsAr1bPsVDo5Ziin3NNOwRsiGRZFO3j-A1SGjkAAT0Qjbw_WD6YDX3dYiw3VoAuNrXd5tmlgft040qfW-fjcJHMmwuPMKXTmoziKcslhC_9WE2USJjieKN3NJ6YGW2KfqgMYbe5FasgKZ5DrwqDLymJbcnnKftuyO31sL9GQlrfUIaKuj3BYh7Nn9vbLzZrxZ0z6da9sG9cZgX8bWKz3eA_Tq9HvZemW2bI-ZG4NeS1kVQgjHcrdQLg1OqsoKIbWc57hoe1dqZ-Ol2QsjEfuwMq8X1lif20YjT_dE75E-Jmmhg4y2r-ffK3xqygA_4QTKUyWUW6IPe9bITJHMOu2ycpznFgbU9IK4VxcLwlKfo_3Ce4PdqZ7WNmdXaixxHltf4f62u3O0n5l1DMeZ4WuAafg8Aq-7sQEA2I0f2qwKPg3SRQtHZPAqtq8XkhXxBucTTS6XPO24ZpFlrAa9nbFc7FtTlsK54W9JZ_nWlvHv6C9meQv5yV70ZMmoKIYeko_6JJwx9nTnHPgwP7Tpur-Oal3ZFYEvgGKH721SQEK1iL1Alicwvhtaf5PDGEAUJ2ZcXr8ZEHmze4bxspCLkoTpIVW1iMYEOJKwqFqpYwosUsTo4YAnWceO2CPjMuAHTj45aZf7BygMcCezCmMw=w848-h182-no)

Let me know if you can see this. My environment is a cloudera data science workbench which has some jupyter elements but cannot display interactive outputs (kind of like the spyder ipython console)

**Comment by FavioVazquez** [comment]
Oh I see now. The output out the profiler is built completely on Jupyter notebook functionalities and javascript, so right now we are not planning on launching it for just a text. For that the only thing I can recommend is that you use the .describe() function in Spark

**Comment by Sarickshah** [comment]
Thanks @FavioVazquez for the swift reply
