### ISSUE TITLE
Create Benchmarks for Optimus (local and cluster)

### ISSUE THREAD

**Issue by FavioVazquez** [ironmussa/Optimus#23]
Try out some cleaning operations in local mode and cluster mode. See performance and create basic graphs.

Principal libraries and frameworks to try:

- Trifacta
- Pandas
- Dora
....

**Comment by argenisleon** [comment]
We plan to do this as a selling point for Optimus but analyzing this now seems that we are comparing apples/pears. Maybe we could just describe the limitations of every platform instead of a benchmark.
Closing this.
