### ISSUE TITLE
Importerror 

### ISSUE THREAD

**Issue by maresk** [ironmussa/Optimus#231]
Anyone seeing this error ? Getting import error 

` cannot import name '_to_unmasked_float_array'` after installation.

**Comment by FavioVazquez** [comment]
Which version are you using? I don't have that problem. Can you send the code for reproducibility?

**Comment by maresk** [comment]
I am using optimuspyspark==1.2.4. It happens right after the import 

`ImportError: cannot import name '_to_unmasked_float_array'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-49712> in <module>()
----> 1 import optimus

/databricks/python/lib/python3.5/site-packages/optimus/__init__.py in <module>()
      2 from optimus.df_transformer import DataFrameTransformer
      3 # Importing DataFrameAnalyzer library
----> 4 from optimus.df_analyzer import DataFrameAnalyzer
      5 # Importing DfProfiler library
      6 from optimus.df_analyzer import DataFrameProfiler

/databricks/python/lib/python3.5/site-packages/optimus/df_analyzer.py in <module>()
      6 from pyspark.ml.stat import Correlation
      7 # Importing plotting libraries
----> 8 import matplotlib.pyplot as plt
      9 import seaborn as sns
     10 # Importing numeric module

/databricks/python/lib/python3.5/site-packages/matplotlib/pyplot.py in <module>()
     30 from cycler import cycler
     31 import matplotlib
---> 32 import matplotlib.colorbar
     33 from matplotlib import style
     34 from matplotlib import _pylab_helpers, interactive

/databricks/python/lib/python3.5/site-packages/matplotlib/colorbar.py in <module>()
     30 
     31 import matplotlib as mpl
---> 32 import matplotlib.artist as martist
     33 import matplotlib.cbook as cbook
     34 import matplotlib.collections as collections

/databricks/python/lib/python3.5/site-packages/matplotlib/artist.py in <module>()
     14 import matplotlib
     15 from . import cbook, docstring, rcParams
---> 16 from .path import Path
     17 from .transforms import (Bbox, IdentityTransform, Transform, TransformedBbox,
     18                          TransformedPatchPath, TransformedPath)

/databricks/python/lib/python3.5/site-packages/matplotlib/path.py in <module>()
     24 
     25 from . import _path, rcParams
---> 26 from .cbook import (_to_unmasked_float_array, simple_linear_interpolation,
     27                     maxdict)
     28 

ImportError: cannot import name '_to_unmasked_float_array'`
