### ISSUE TITLE
`Normalizer` only works with dense vectors

### ISSUE THREAD

**Issue by deepakjangid123** [ironmussa/Optimus#269]
Hi all,

A function for normalization (`normalizer`) is defined in `optimus.spark.df_transfomer.py` which only works with dense Vectors.
And unfortunately we don't have any datatype like this for a dataframe.
Possible datatypes are `[ "NullType", "StringType", "BinaryType", "BooleanType", "DateType",    "TimestampType", "DecimalType", "DoubleType", "FloatType", "ByteType", "IntegerType",
    "LongType", "ShortType", "ArrayType", "MapType", "StructField", "StructType"]`. [(here)](http://spark.apache.org/docs/2.1.0/api/python/_modules/pyspark/sql/types.html)

So it will be helpful if we can extend `normalizer` to work with `ArrayType()` fields also OR share schema with me for a dataframe on which I can apply `normalizer`. Let me know if there is an alterative way to this else, can I send a PR to support `ArrayType()` also.

Thanks

**Comment by argenisleon** [comment]
Hi @deepakjangid123,

All the PR all welcome :D.

**Comment by FavioVazquez** [comment]
I will close the issue when the new version is submitted.

**Comment by FavioVazquez** [comment]
New version is up and running. You can download it now from PyPI. Check https://github.com/ironmussa/Optimus/releases/tag/1.2.6
