### ISSUE TITLE
Running profiler on relatively small file errors at the end

### ISSUE THREAD

**Issue by ronbuchanan** [ironmussa/Optimus#316]
Environment: Databricks, Azure, Python

Following the example @ https://github.com/ironmussa/Optimus/blob/master/examples/new-api-profiler.ipynb, I parsed a delimited file and called `op.profiler.run(...)` and let her ride.

The first round on a 2G file, with  151 columns never seemed to finish after about 45mins of running. I was up to 39 Spark jobs when I decided to kill it.

I tried a different file roughly the same size and specified 7 columns to process. It took 43 Spark jobs and 45 mins to run profiler on that file.

In the end, I get an error 

```
TemplateNotFound                          Traceback (most recent call last)
<command-2749932586049532> in <module>()
      8 df_raw = op.read.csv("/mnt/lake/passport_ky/members/MCAID_MEMBER_05102018_01.txt", header=True, sep="|")
      9 
---> 10 op.profiler.run(df_raw, ["MEMBER_KEY","MemberID","BirthDate","MemberLastName","MemberFirstName","SSN","Gender"])

/databricks/python/lib/python3.5/site-packages/optimus/profiler/profiler.py in run(self, df, columns, buckets)
    276         # Create the profiler info header
    277         html = ""
--> 278         general_template = template_env.get_template("general_info.html")
    279         html = html + general_template.render(data=output)
    280 

/databricks/python/lib/python3.5/site-packages/jinja2/environment.py in get_template(self, name, parent, globals)
    828         if parent is not None:
    829             name = self.join_path(name, parent)
--> 830         return self._load_template(name, self.make_globals(globals))
    831 
    832     @internalcode
```

Beyond the error I am getting, does this performance seem normal?

**Comment by argenisleon** [comment]
Hi @ronbuchanan,

Thanks for the feedback. A couple of question below.

1.- How many rows are you processing?
2.- We have an error when packing the pip file and the .html files were not included. Is it possible for you to use the version in the develop branch https://github.com/ironmussa/Optimus/tree/develop? In case that not, we expect to release a new version tomorrow fixing this issue.

**Comment by ronbuchanan** [comment]
Thanks for the quick response!

I think the real issue is the size of the dataset, since it was a few million. Is there a particular threshold to stay under for Optimus? It is US healthcare data, so the more I can sample, the better.

I see you have a setup.py, I should be fine. I just have to package and upload.

Let me know when you get the new version out and I will test it out. Really looking forward to seeing what I can do with Optimus.

**Comment by argenisleon** [comment]
Hi @ronbuchanan,

Do you have any improvement with the new version?

**Comment by ronbuchanan** [comment]
Apologies for my delay in responding. I have not tested the latest versions yet. I have been detoured for a bit, but plan on getting back to it in the next few days.
