### ISSUE TITLE
OneHotEncoder

### ISSUE THREAD

**Issue by eysdevteam** [ironmussa/Optimus#355]
Hola, quisiera saber si tienen planeado realizar un cambio en la importación de librerias que usan en ml.features, ya que como saben el OneHotEncoder será remplazado por OneHotEncoderEstimator.
Gracias.

**Comment by FavioVazquez** [comment]
Si así es. Estamos preparando la nueva versión con 2.3.2 gracias!

**Comment by FavioVazquez** [comment]
Muchas gracias! La versión nueva viene con varios tweaks interesantes :)
