### ISSUE TITLE
Create qqplots

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#380]
![image](https://user-images.githubusercontent.com/37144/47610992-e9bfac80-da28-11e8-870c-5842d1431bfb.png)

**Comment by aviolante** [comment]
Hey @argenisleon are you currently working on this? I may have a solution but I can run it past you before hand. Thanks!

**Comment by aviolante** [comment]
I'm using a pointing to a pandas dataframe for this so maybe not what you guys are looking for. Happy to help though.

![Screen Shot 2019-06-24 at 4 23 04 PM](https://user-images.githubusercontent.com/13370368/60049541-80b63480-969c-11e9-91b1-5ebf045fafe4.png)

**Comment by argenisleon** [comment]
Hi @aviolante.
We need to ensure that plotting the point is scalable. Maybe some sampling can help? @FavioVazquez  what do you think?

**Comment by aviolante** [comment]
Thats a good point @argenisleon. I can limit it. I'm trying to figure out how to do the exact approach above using an optimus dataframe versus a pandas one. Sorry for the early excitement haha.

**Comment by aviolante** [comment]
Added in a sample size param for percent to sample.

`plot_qqplots(dataframe=data, grid_rows=3, grid_cols=3, sample_size=0.4)`

**Comment by argenisleon** [comment]
Sounds great,

Can you make a PR so we can view the code you are working? 😁

**Comment by aviolante** [comment]
Sure thing @argenisleon . functions.py file?

**Comment by aviolante** [comment]
Here you go @argenisleon 

https://github.com/ironmussa/Optimus/pull/574

**Comment by argenisleon** [comment]
Hi @aviolante,

Thanks for your contribution. qqplots are now available in Optimus
