### ISSUE TITLE
Unable to install to install Optimus

### ISSUE THREAD

**Issue by cpatte7372** [ironmussa/Optimus#391]
Hello all,

I'm really excited about what I've read about Optimus. Unfortunately, I'm coming across a number of issues getting it up and running. 

I have followed the instructions here:

https://medium.com/hi-optimus/how-to-install-jupyter-notebook-4-4-0-and-optimus-on-ubuntu-18-04-92ff5ef30ea4

However, whenever i try to issue the following script to my notebook I get the following error:

import optimus as op

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0f272e8fc6d6> in <module>()
----> 1 import optimus as op

ModuleNotFoundError: No module named 'optimus'

Im running python 3.6

I feel that this is a simple error that I have made, but I'm at a loss.

Any help will be greatly appreciated.

Cheers

**Comment by FavioVazquez** [comment]
Hi! Thanks for the interest. That post it’s a little outdated. You can run:

pip install optimuspyspark 

And then check the examples from the master branch!

You have to do a different import now. 

Please let me know if this work for you! :)

**Comment by cpatte7372** [comment]
Hi FavioVazquez,

Thanks for reaching out. I'm sure I'm tried your suggestion and it didn't work out ... going to try it again now and let you know.

**Comment by cpatte7372** [comment]
OK, 

I'm not getting the following error from the terminal when I issue the following command after installing pip install optimuspyspark from https://github.com/ironmussa/Optimus


from optimus import Optimus
op = Optimus()

packt@ubuntu-c:~/.local/lib/python3.5/site-packages/optimus$ from optimus import Optimus
from: can't read /var/mail/optimus
packt@ubuntu-c:~/.local/lib/python3.5/site-packages/optimus$ op = Optimus()
bash: syntax error near unexpected token `('
packt@ubuntu-c:~/.local/lib/python3.5/site-packages/optimus$

**Comment by cpatte7372** [comment]
Sorry, I meant to say I'm **NOW** getting the following error from the terminal when I issue the following command after installing pip install optimuspyspark from https://github.com/ironmussa/Optimus

from optimus import Optimus
op = Optimus()

packt@ubuntu-c:/.local/lib/python3.5/site-packages/optimus$ from optimus import Optimus
from: can't read /var/mail/optimus
packt@ubuntu-c:/.local/lib/python3.5/site-packages/optimus$ op = Optimus()
bash: syntax error near unexpected token `('
packt@ubuntu-c:~/.local/lib/python3.5/site-packages/optimus$

**Comment by cpatte7372** [comment]
Any thoughts?

**Comment by cpatte7372** [comment]
I tried to install on another unbuntu with the command sudo pip install optimuspyspark and I got the following error:
```
packt@ubuntu2:~$ sudo pip install optimuspyspark
The directory '/home/packt/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/packt/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting optimuspyspark
  Downloading https://files.pythonhosted.org/packages/56/6a/93e4f3cedb245028820915173d932e2002cb6121a60c2cab6b013963cc91/optimuspyspark-2.1.3.tar.gz (82kB)
    100% |████████████████████████████████| 92kB 269kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ust1jm/optimuspyspark/setup.py", line 14, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ust1jm/optimuspyspark/
packt@ubuntu2:~$ 

```

**Comment by cpatte7372** [comment]
Any help will be greatly appreciated

**Comment by cpatte7372** [comment]
Hi, I managed to get this up and running. However, when I go through the example shown here 
https://github.com/ironmussa/Optimus

I run the command df.cols.replace("product","taaaccoo","taco")\ but there isn't any change to the table

Any reasons why?

**Comment by argenisleon** [comment]
hi @cpatte7372 
It should work, I just execute

```
df =op.load.url("https://raw.githubusercontent.com/ironmussa/Optimus/master/examples/data/foo.csv")
df.table()
```

![image](https://user-images.githubusercontent.com/37144/48307388-5353b680-e511-11e8-95bc-eec2aaf6bf09.png)


```
def func(value, arg):
    return "this was a number"
    
df\
    .rows.sort("product","desc")\
    .cols.lower(["firstName","lastName"])\
    .cols.date_transform("birth", "yyyy/MM/dd", "dd-MM-YYYY")\
    .cols.years_between("birth", "yyyy/MM/dd")\
    .cols.remove_accents("lastName")\
    .cols.remove_special_chars("lastName")\
    .cols.replace("product","taaaccoo","taco")\
    .cols.replace("product",["piza","pizzza"],"pizza")\
    .rows.drop(df["id"]<7)\
    .cols.drop("dummyCol")\
    .cols.rename(str.lower)\
    .cols.apply_by_dtypes("product",func,"string", data_type="integer")\
    .cols.trim("*")\
    .table()
```
![image](https://user-images.githubusercontent.com/37144/48307404-91e97100-e511-11e8-91b5-971813dd4fc5.png)

Is this what you expect?

**Comment by cpatte7372** [comment]
Hi ironmussa,

 

This worked perfectly, thanks.

 

I just have a few learning questions:

 

1.	Can you explain what exactly the following command set out to achieve:

               def func(value, arg):

    return "this was a number

2.	Is there place where I can find all the switches e.g. remove_special_chars, remove_accents, years_between.

 

 

Thanks

 

Carlton

**Comment by cpatte7372** [comment]
Hi argenisleon, 

Any idea where I can find more cleansing examples?

Can you let me know where I can find a list of switches as shown below?
.cols.remove_accents
.cols.replace
 .cols.rename

Thanks

**Comment by argenisleon** [comment]
@cpatte7372 
About the first question:
```
def func(value, arg):
    return "this was a number"
```

Is a function applied all the integers in the 'product' column. More especicaflly in transform all  integers to the string "this was a number"
```
.cols.apply_by_dtypes("product",func,"string", data_type="integer")
```

2. You can find all the columns and row operacions [here](https://github.com/ironmussa/Optimus/blob/master/examples/new-api-column.ipynb) and [here](https://github.com/ironmussa/Optimus/blob/master/examples/new-api-row.ipynb)

You also can find a lot of examples and uses cases in the [examples folder](https://github.com/ironmussa/Optimus/tree/master/examples)

Hope this help

**Comment by cpatte7372** [comment]
@argenisleon 

thanks for the information, that's great.

I'm trying to run the same commands from my Databricks workspace notebook (as you probably know Databricks is built on Spark and uses the same principle as Jupyter Notebook).

I issue the following commands:
```
!pip install optimuspyspark
!from optimus import Optimus
!op= Optimus()
!df =op.load.url("https://raw.githubusercontent.com/ironmussa/Optimus/master/examples/data/foo.csv")
!table()

```
However, there isn't any output. Do you have any idea why?

Cheers

**Comment by argenisleon** [comment]
@FavioVazquez can you please look at this?

**Comment by argenisleon** [comment]
@cpatte7372 Did you solve the problem?

**Comment by cpatte7372** [comment]
@argenisleon this fixed the problem.

Thank you
