### ISSUE TITLE
ImportError: cannot import name 'Optimus' from 'optimus' (unknown location)

### ISSUE THREAD

**Issue by nadeemnehru** [ironmussa/Optimus#446]
The error is raised on executing "from optimus import Optimus". I'm running Python 3.7.2

**Comment by argenisleon** [comment]
Hi @nadeemnehru ,

It seems that Optimus is not installed or the library python path is set correctly. Can you check that the path is pointing to where Optimus is installed?

**Comment by nadeemnehru** [comment]
Thanks @argenisleon 

Being a beginner, I hope following is the information you need

Here is the output from pip freeze

(python372) applied@nadeem-Inspiron-5558:~$ pip freeze
absl-py==0.7.0
amqp==2.4.0
asn1crypto==0.24.0
astor==0.7.1
attrs==18.2.0
Automat==0.7.0
backcall==0.1.0
backoff==1.8.0
bleach==3.1.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
colorama==0.4.1
constantly==15.1.0
cryptography==2.4.2
cssselect==1.0.3
cycler==0.10.0
cymem==2.0.2
Cython==0.29.3
cytoolz==0.9.0.1
decorator==4.3.0
defusedxml==0.5.0
Deprecated==1.2.4
dill==0.2.9
en-core-web-sm==2.0.0
entrypoints==0.3
fastnumbers==2.1.1
findspark==1.3.0
future==0.17.1
fuzzywuzzy==0.17.0
gast==0.2.2
grpcio==1.18.0
h2o-pysparkling-2.4==2.4.4
h5py==2.9.0
hyperlink==18.0.0
idna==2.8
incremental==17.5.0
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.2
jellyfish==0.7.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.8
kiwisolver==1.0.1
kombu==4.2.2.post1
lxml==4.3.0
Markdown==3.0.1
MarkupSafe==1.1.0
matplotlib==3.0.1
mistune==0.8.4
msgpack==0.5.6
msgpack-numpy==0.4.3.2
murmurhash==1.0.1
nbconvert==5.4.0
nbformat==4.4.0
nose==1.3.7
notebook==5.7.4
numexpr==2.6.9
numpy==1.15.2
pandas==0.23.4
pandocfilters==1.4.2
parsel==1.5.1
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.5
pika==0.12.0
pipenv==2018.11.26
plac==0.9.6
preshed==2.0.1
prometheus-client==0.5.0
prompt-toolkit==2.0.7
protobuf==3.6.1
ptyprocess==0.6.0
py4j==0.10.7
pyasn1==0.4.5
pyasn1-modules==0.2.3
pycparser==2.19
PyDispatcher==2.0.5
Pygments==2.3.1
PyHamcrest==1.9.0
pyOpenSSL==18.0.0
pyparsing==2.3.1
pyspark==2.3.1
python-dateutil==2.7.5
pytz==2018.9
pyzmq==17.1.2
qtconsole==4.4.3
queuelib==1.5.0
ratelimit==2.2.1
recordlinkage==0.12
regex==2018.1.10
requests==2.21.0
scikit-learn==0.20.2
scipy==1.2.0
Scrapy==1.5.1
seaborn==0.9.0
selenium==3.141.0
Send2Trash==1.5.0
service-identity==18.1.0
six==1.12.0
spacy==2.0.18
tabulate==0.8.2
tensorboard==1.10.0
tensorflow==1.10.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
thinc==6.12.1
toolz==0.9.0
tornado==5.1.1
tqdm==4.30.0
traitlets==4.3.2
Twisted==18.9.0
ujson==1.35
urllib3==1.24.1
vine==1.2.0
virtualenv==16.2.0
virtualenv-clone==0.5.0
w3lib==1.19.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.2
wrapt==1.10.11
zope.interface==4.6.0

and it seems PYTHONPATH is not set as indicated by the bellow command

echo $PYTHONPATH

(python372) applied@nadeem-Inspiron-5558:~$

**Comment by argenisleon** [comment]
@nadeemnehru check this https://stackoverflow.com/questions/135035/python-library-path

**Comment by nadeemnehru** [comment]
Thanks @argenisleon 
I checked sys.path. I could not find Optimus in any of the locations present in sys.path

**Comment by argenisleon** [comment]
Can you try adding the Optimus folder to your PYTHONPATH?

**Comment by nadeemnehru** [comment]
Thanks @argenisleon 
Hope I don't sound stupid, I don't know how to find the Optimus folder

**Comment by argenisleon** [comment]
Please try:
`python -m site`
to check your folders. Look for a folder with this strcuture
`<virtualenv_name>/lib/<python_ver>/site-packages`

If you are using Optimus from a notebook run `!python -m site` from a cell so you can be sure about the _env_ you are using.

**Comment by nadeemnehru** [comment]
Thanks @argenisleon 
I checked the specific folder. Apparently I can't see Optimus. Here is the listing of the folder.

(python372) applied@nadeem-Inspiron-5558:~$ ls python372/lib/python3.7/site-packages/ | grep Optimus
(python372) applied@nadeem-Inspiron-5558:~$

**Comment by argenisleon** [comment]
Are you sure that Optimus installed without problems?

**Comment by nadeemnehru** [comment]
@argenisleon 
When installing Optimus using "pip install optimuspyspark", I got different errors many times such as issues with installation of tensorflow, pyarrow, and others. On resolving an issue somehow, I would run "pip install optimuspyspark" again till issues were resolved. I am not sure though whether all the issues got resolved and whether optimus installation finished successfully
