### ISSUE TITLE
Issues with required package installations

### ISSUE THREAD

**Issue by akhilrj** [ironmussa/Optimus#457]
Hi,

I am on MacOS Mojave and when I tried to install Optimus, I received error in the following dependent packages:

1. Tensorflow (Could not find Tensorflow==1.12.0)
2. Pyarrow (Error while running cmake)

Thnaks!!

**Comment by argenisleon** [comment]
Hi @akhilrj,
Which python version are you using? It seems that pyarrow 0.10 does not work with python greater than 3.6. Check this  https://github.com/apache/arrow/issues/1125
