### ISSUE TITLE
Py4JJavaError: An error occurred while calling z:org.apache.spark.util.SizeEstimator.estimate.

### ISSUE THREAD

**Issue by SheldonGrant** [ironmussa/Optimus#460]
I find that there is an error when running the optimus.profiler.
When the profiler attempts to compute the dataframe size here:
       167     java_obj = _to_java_object_rdd(self.rdd)
       168 
--> 169     n_bytes = Spark.instance.sc._jvm.org.apache.spark.util.SizeEstimator.estimate(java_obj)
      170     return n_bytes

Not sure if there is an issue here with the implementation of _to_java_object_rdd and it perhaps does not produce the correct java_obj or if some other issue exists with SizeEstimator. More likely the former.

Thanks, appreciate the help.

**Comment by argenisleon** [comment]
HI @SheldonGrant,

Which Java and Spark do you have?

**Comment by SheldonGrant** [comment]
thanks for the quick reply.

I am using python 3.6 

with 
optimuspyspark==2.1.5
pyspark==2.4.0
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)

Could this be the issue? Though the requirements seem to be Spark 2.4.0. & using python 3.6. Not seeing the java version

**Comment by argenisleon** [comment]
Hi @SheldonGrant,

The problem seems java >8 and seems to be related to this. https://issues.apache.org/jira/browse/SPARK-24421

We expect to upload a patch soon
