### ISSUE TITLE
on moving the column to the start of the column throws exception.

### ISSUE THREAD

**Issue by pallav1991** [ironmussa/Optimus#473]
in Optimus/dataframe/Columns.py
Under move(column, position, ref_col)
@line 356 need to change new_index[0] to new_index

**Comment by FavioVazquez** [comment]
@argenisleon can you take a look please?

**Comment by argenisleon** [comment]
Hi @pallav1991, can you give us some python code that help us to replicate this?

**Comment by pallav1991** [comment]
Thank You.
