### ISSUE TITLE
Loading data from multi-line json file.

### ISSUE THREAD

**Issue by GabrielOrAnder** [ironmussa/Optimus#475]
Not sure if it's an issue but i'd got an Error when i tried load the Json file below using op.load.json("file-path.json"):
```
[{"Id":1, "Nome":"Item 1"}
,{"Id":2, "Nome":"Item 2"}
,{"Id":3, "Nome":"Item 3"}
]
```
But works when i change the file structure to one-line.

**Comment by FavioVazquez** [comment]
What's the error you are getting?

**Comment by argenisleon** [comment]
I am working on this right now. I was able to replicate this error referred here https://stackoverflow.com/questions/49427623/could-not-read-data-from-json-using-pyspark.

@GabrielOrAnder can you confirm this?

**Comment by FavioVazquez** [comment]
Apparently the issue can be fixed using `multiLine=True`. Maybe we can add a **kwargs for making this option available.

**Comment by GabrielOrAnder** [comment]
@argenisleon, here is the Error i'd received:

```
Py4JJavaError: An error occurred while calling o49.collectToPython.
: org.apache.spark.sql.AnalysisException: Since Spark 2.3, the queries from raw JSON/CSV files are disallowed when the
referenced columns only include the internal corrupt record column
(named _corrupt_record by default). For example:
spark.read.schema(schema).json(file).filter($"_corrupt_record".isNotNull).count()
and spark.read.schema(schema).json(file).select("_corrupt_record").show().
Instead, you can cache or save the parsed results and then send the same query.
For example, val df = spark.read.schema(schema).json(file).cache() and then
df.filter($"_corrupt_record".isNotNull).count().;
```
