### ISSUE TITLE
while splitting the column with regex expression without giving the split number the logic is incorrect.

### ISSUE THREAD

**Issue by pallav1991** [ironmussa/Optimus#492]
Hello,
I am splitting the column by providing the regex.
The logic works correct if i provide `splits` but what if i don't want to give the number of the columns it should split.
It should split into `n` columns according to the regex i provided.

My issue works when i change in [column.py](https://github.com/ironmussa/Optimus/blob/master/optimus/dataframe/columns.py) file at line number `#1255`
from 
`splits = len(self.cols.cell(col_name).split(mark))`
to 
`splits = len(re.split(mark, self.cols.cell(col_name)))`

For example
I have a column with below data
`XRQ-TRUCK GROUND`
`ZY-EXPRESS`

Now I want to split this column with `[\-\_\ ]` (Note: there is also a space there). the output of this column can be 1/2/3...n columns.

**Comment by FavioVazquez** [comment]
@argenisleon can you check this please?

**Comment by argenisleon** [comment]
Hi @pallav1991,

Thanks, I am going to check to integrate this.

**Comment by argenisleon** [comment]
Hi @pallav1991,

Looking into the issue, it seems that you are looking into "dynamic spitting".
Maybe you need this?. https://stackoverflow.com/questions/39235704/split-spark-dataframe-string-column-into-multiple-columns

What you comment about line #1255 only try to infer the number of splits based in the first column row.

What do you think?

**Comment by pallav1991** [comment]
yes,
It seems that i need to implement this. thanks for the reference link. 

I think there is still an issue there 
lets say that i have a below string in the first row cell i want to split
`CARD; 4.75X7.5;`

now what i do is use the the unnest function to split the column with regex expression `[;.]`
the line at no. #1255 returns the length of 1.
where as at line no. #1252 `expr = F.split(F.col(col_name), mark)` splits the data.

then at line no. #1263 `df = df.withColumn(col_name + "_" + str(i), expr.getItem(i))`
this line adds the column with only `CARD` as my data.
Can you please check this.
Please let me know if i am unclear.

**Comment by argenisleon** [comment]
Ok, I got it,

The change you propose seems enough to handle this. Could you make a PR?

About dynamic splitting, a contribution is welcome. Are you able to work on this? 
Let me know if I could help

**Comment by argenisleon** [comment]
Hi @pallav1991,
Thank for the PR. Are you planning to work on the dynamic splitting? It would be amazing if optimus could handle it

**Comment by pallav1991** [comment]
Hi @argenisleon,
Yes I am planning to work on dynamic splitting, I have few things lined up once i finished with that (in around week or so) i will work on it.
