### ISSUE TITLE
Integrate mlflow to Optimus

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#502]
It would be great if Optimus could serialize, deploy models and have all the tools to make the process as easy as possible.

**Comment by wilmeragsgh** [comment]
Is this for creating a built-in flavor for Optimus on MLflow ? or using MLflow here?

**Comment by argenisleon** [comment]
@wilmeragsgh I missed this message. The idea is how we can use mflow I what work is needed to deploy models easily.

I have not explored mflow in deep. Any idea about this?

**Comment by argenisleon** [comment]
Closing at the moment we are focusing on data processing
