### ISSUE TITLE
convert spark dataframe to Optimus

### ISSUE THREAD

**Issue by sophia-wright-blue** [ironmussa/Optimus#513]
thanks for releasing this amazing repo: I have a very basic question:

I'd like to read in my data and create a dataframe with Spark. I do a few data preprocessing steps on this Spark dataframe. I now have a Spark dataframe that I'd like to use with the functionality available with Optimus, so how do I convert a Spark dataframe so I can use it as if it were created by reading in the data directly with Optimus?

Hope that makes sense. Thanks,

**Comment by argenisleon** [comment]
Hi @sophia-wright-blue,

We are working is something like this:
```
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('abc').getOrCreate()
df=spark.read.csv('data/foo.csv',header=True)

from optimus import Optimus
op = Optimus(spark)

# Here do you have all Optimus functionality (except DL)
df.table()
```
What do you think?

**Comment by sophia-wright-blue** [comment]
That'd be very helpful, currently I use the library handyspark (https://github.com/dvgodoy/handyspark), and that has something similar, where we need to do 

`hdf = sdf.toHandy()`

where `sdf` is a spark dataframe; 

I'm assuming there is also a plan to convert back to Spark dataframe?

Looking forward to this change; Thanks again for releasing this repo - I hope to see more updates on Optimus

**Comment by argenisleon** [comment]
Thanks for the feedback @sophia-wright-blue,
I am not sure how handyspark works but in Optimus, a df is always a Spark Dataframe. Optimus monkey patch the Spark df to add new functions.

Can you explain a little why you need to convert back to a Spark Dataframe?

**Comment by sophia-wright-blue** [comment]
I have an existing workflow in PySpark where I'd like to use the existing code for data pre-processing and post-processing ; I'd like to add to this workflow using all of the functionality available in Optimus; thanks for the prompt reply @argenisleon

**Comment by argenisleon** [comment]
You do not have to change anything to add Optimus to your workflow. I'll be pushing this feature today

**Comment by sophia-wright-blue** [comment]
thanks for the prompt replies @argenisleon , i'll follow https://github.com/ironmussa/Optimus/pull/516
