### ISSUE TITLE
Handling column names when creating new data

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#514]
When operations generate new data the target columns can be:

* The actual column
* A new column named by the user
* Auto named column in case an operation is applied to multiple columns
* Manually named multiple columns

We need to define how the user is going to handle this. Actually, some methods create new columns and some not.

**Comment by wilmeragsgh** [comment]
Is it a specific example/use case where you see this? i would like to propose some ideas to see what you think based on those scenarios

**Comment by argenisleon** [comment]
Hi @wilmeragsgh,

This works like this:
```
# Cast in the same column
df.cols.cast("col_1,","str")

# Cast and create col_new
df.cols.cast("col_1,","str",output_cols="col_new")

# Cast multiple columns to col_1_new, col_2_new, col_3_new
df.cols.cast(["col_1","col2","col3"],"str",output_cols="_new")

# Cast multiple columns to col_1_new, col_2_new, col_3_new
df.cols.cast(["col_1","col2","col3"],"str",output_cols=["col_1_new","col_2_new", "col_3_new])
```
It's implemented in all the methods that affect columns like 'replace', 'impute','fill_na' and some others. You can check this on https://github.com/ironmussa/Optimus/blob/develop/optimus/dataframe/columns.py

We hope soon have this merged into master. What do you have in mind?

**Comment by wilmeragsgh** [comment]
Oh alright, just wanted to help with this: 

> We need to define how the user is going to handle this. Actually, some methods create new columns and some not.

But seems pretty stable for the moment.
