### ISSUE TITLE
Manejando variables categoricas

### ISSUE THREAD

**Issue by EdgarSanchez1796** [ironmussa/Optimus#532]
Hola, quisiera saber si con el metodo usado para procesar las variables categoricas puede pasar que el algoritmo interperete que por ejemplo una categoria con indice 10, es mejor que una categoria con indice 2.

Gracias.

**Comment by argenisleon** [comment]
@FavioVazquez can you take a look on this?

**Comment by EdgarSanchez1796** [comment]
Sorry.
I want to know if the method used in the library to process the categorical variables could assume that a category with index 10 is better that a second category with a index 2, so if it assume that the transformed features are ordinals. Thanks

**Comment by FavioVazquez** [comment]
Hola @EdgarSanchez1796. Te refieres a si el método que usamos puede decirte si una variable es mejor a otra?

**Comment by EdgarSanchez1796** [comment]
@FavioVazquez Excactamente, es decir que por ejemplo tenga
COLOR 
verde   ---  1
verde   ---  1
rojo     ---  2

Y que se interprete como que rojo es mayor que verde.

Es conocido que python tiene un problema aun con las variables categoricas, no? 
Yo quiera saber si el metodo bajo esta librería que proviene de spark, mitiga ese problema 

Gracias por responder

**Comment by davsuacar** [comment]
Una pregunta, ¿Cuál es el método usado para tratar variables categóricas? Es que no lo veo en la doc. Gracias

**Comment by FavioVazquez** [comment]
@argenisleon podrías revisar esto por favor?

**Comment by FavioVazquez** [comment]
Hola @EdgarSanchez1796  y @davsuacar voy a asumir que se refieren a algo como string_to_index, la función que tenemos en Optimus.

En este caso proviene directamente de StringToIndex de Spark, y por defecto lo que hace la función es hacer un ordenado por orden descendente por frecuencia de etiqueta (etiqueta asignada con mayor frecuencia 0). Pero esto puede cambiarse con los diferentes métodos que tiene el método. Acá pueden ver todos los tipos:

-"frequencyDesc” (default): descending order by label frequency (most frequent label assigned 0), 
- “frequencyAsc”: ascending order by label frequency (least frequent label assigned 0), 
- “alphabetDesc”: descending alphabetical order, 
-  “alphabetAsc”: ascending alphabetical order

Espero eso responda su pregunta. Sino por favor díganme. 

Saludos!
