### ISSUE TITLE
I am getting below exception while reading csv file and writing it to parquet file

### ISSUE THREAD

**Issue by pallav1991** [ironmussa/Optimus#547]
Today After Upgrade when I ran my Program I am getting below exception.
```

{Py4JJavaError}An error occurred while calling o125.parquet.
: java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SQLConf$.LEGACY_PASS_PARTITION_BY_AS_OPTIONS()Lorg/apache/spark/internal/config/ConfigEntry;
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:277)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:566)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.comm...


```

Can you tell me why is this  exception occurring.

**Comment by argenisleon** [comment]
Can you put here the exactly code you are using?

**Comment by pallav1991** [comment]
`
            if self.requestSubType == "createCSVToParquet":
                df = self.manager.optimus.load.csv(self.filePath)
            elif self.requestSubType == "createExcelToParquet":
                df = self.manager.optimus.load.excel(self.filePath, self.sheetName)

            if df is not None:
                df = convertColumnParquetFormat(df)
                df.write.mode("overwrite").parquet(self.haddopPath + self.fileName + '.parquet')
                return "success"
            return "failed"
`

**Comment by argenisleon** [comment]
It seems like some kind of bug
Can you save the data successfully to another format like csv?
Can you try:
```
self.manager.optimus.save..parquet(self.haddopPath + self.fileName + '.parquet')
```
It almost the same as the native spark save plus a couple of checks

**Comment by argenisleon** [comment]
Hi @pallav1991, this works for you?

**Comment by rajib76** [comment]
is this bug fixed? i am also getting this

**Comment by argenisleon** [comment]
Hi @rajib76, are you getting the same error? the code @pallav1991 provide use 
```df.write.mode("overwrite").parquet(self.haddopPath + self.fileName + '.parquet')``` a pyspark code not optimus code.

Did you try:
```optimus.save.parquet(self.haddopPath + self.fileName + '.parquet')```

If that not work can you show us your code?

**Comment by pallav1991** [comment]
> optimus.save

sorry @argenisleon for the late reply.
I have a question before i execute the above request.
in the above code where am i specifying the dataframe to write on the parquet file.

**Comment by argenisleon** [comment]
Mi bad,

The correct code is:
```df.save.parquet(self.haddopPath + self.fileName + '.parquet')```
