### ISSUE TITLE
Issue with installing optimuspyspark

### ISSUE THREAD

**Issue by IshanDindorkar** [ironmussa/Optimus#551]
Hi Team -

I am in the middle of installing optimuspyspark package to experiment with data cleaning / analysis aspects of the library. Unfortunately, I am facing some issue during installation. I used following command for installation -

python3 -m pip --proxy <proxy-url> install optimuspyspark

I am seeing this error post executing the command -

----------------------------------------------------------------------------------------------------------
Collecting pyspark==2.4.1 (from optimuspyspark)
  Using cached https://files.pythonhosted.org/packages/f2/64/a1df4440483df47381bbbf6a03119ef66515cf2e1a766d9369811575454b/pyspark-2.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Could not import pypandoc - required to package PySpark
    Download error on https://pypi.python.org/simple/pypandoc/: [Errno -2] Name or service not known -- Some packages may not be found!
    Couldn't find index page for 'pypandoc' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
    No local packages or download links found for pypandoc
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fhfdbfsj/pyspark/setup.py", line 224, in <module>
        'Programming Language :: Python :: Implementation :: PyPy']
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pypandoc')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fhfdbfsj/pyspark/

----------------------------------------------------------------------------------------------------------

Could you please help in fixing this issue? Thanks in advance.

Best -
Ishan

**Comment by argenisleon** [comment]
Hi @IshanDindorkar,

It seems that it can not find pypandoc  
Can you try:
```
pip install pypandoc
````

then 
```
python3 -m pip --proxy install optimuspyspark
```

Let us know if that works

**Comment by IshanDindorkar** [comment]
Hi @argenisleon -

Thank you for your prompt response. Really appreciate it.
I followed your instructions and installed pypandoc first and then tried again with installing optimuspyspark. This time I am seeing some error log but I think I know what is going wrong in my case -

ERROR: h2o-pysparkling-2-4 2.4.10 has requirement pyspark<=2.4.0,>=2.4.0, but you'll have pyspark 2.4.1 which is incompatible.
ERROR: pyasn1-modules 0.2.5 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.

I am having pyspark version 2.3.* installed on my machine which seems incompatible with optimuspyspark. I cannot upgrade to 2.4.* for some business reason. Could you please advise if there is some workaround so that I can have both - pyspark 2.3.* version and your library.

**Comment by argenisleon** [comment]
Maybe you could:

1. Copy or clone optimus.
2. Goto to the Optimus folder and edit requirements.txt
3. Change pyspark==2.4.1 for pyspark==2.3.x (the version you want)
4. Run ```pip install -r requirements.txt```
5. When you want to work with optimus at the beginning of the script use
```import sys
sys.path.append("..") # ".." is the relative position of optimus. Change accordingly
```
Let me know if this work for you

**Comment by IshanDindorkar** [comment]
It is working great! Thank you so much @argenisleon for your help. I am very impressed with the activeness of team to support people willing to try this library.
