### ISSUE TITLE
Read from tab separated files

### ISSUE THREAD

**Issue by IshanDindorkar** [ironmussa/Optimus#552]
Hi Team -

I started using the library and began with loading my datasets which are in tab-separated format. I observed columns are not as expected. Could you please advise if it is supported as I could not find TSV in the list of supported formats(CSV, JSON ... ) on GitHub page.

Thanks in advance.

Best -
Ishan

**Comment by FavioVazquez** [comment]
Hi @ishandindorkar, with the load.csv or read.csv function you can set the separator to “ “, that should do the trick :)

**Comment by IshanDindorkar** [comment]
Hey @FavioVazquez -

Thanks for your response. I figured that out by looking at the params of load.csv() in source code. I am passing delimiter as "\t" and it is working as expected :)

Best -
Ishan

**Comment by argenisleon** [comment]
Done in development https://github.com/ironmussa/Optimus/blob/develop/optimus/io/load.py#L63
