### ISSUE TITLE
JDBC Connectivity

### ISSUE THREAD

**Issue by IshanDindorkar** [ironmussa/Optimus#557]
Hi Team -

I am trying to dump my dataset into a PostgreSQL and read from it within a Jupyter Notebook. I referred example you provided in your README docs to connect to a database but I am facing difficulty to apply it within a notebook since I am not able to set driver class path. Normally, when I run spark application using "spark-submit" I can point to postgresql driver using runtime argument "driver-class-path" but couldn't find a way to do it through notebook.
FYI, I tried solutions given in various stackoverflow posts like -

# os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars <postgredriver.jar> pyspark-shell'
# os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages org.postgresql:postgresql:42.1.1 pyspark-shell'
# environ['PYSPARK_SUBMIT_ARGS'] = '--driver-class-path <postgredriver.jar> --jars <postgredriver.jar> pyspark-shell'

Could you please help me in getting around this issue.

Thank you.

Best -
Ishan

**Comment by argenisleon** [comment]
Hi @IshanDindorkar ,

I think you can take a couple of approaches here:

You can configure the Spark session with the postgreSQL driver and pass it on to Optimus
```
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('optimus').getOrCreate()
op= Optimus(spark)
```

or we expect to release on the next days a way in which you can create Optimus with jars as params.

Hope this help

**Comment by IshanDindorkar** [comment]
Hi @argenisleon , thanks for your response. Perhaps, I tried to set config as well while initiating spark session, the way you showed but unfortunately it didn’t worked. For some reason, it keeps failing to detect my driver JAR and throw me error - No suitable driver. I will wait for your release and meantime will keep trying if I could get it working. Appreciate your help. Thank you.
Have a good weekend!

**Comment by niteshnicholas** [comment]
Hi, @IshanDindorkar did it worked for you now. In fact, I am facing the same issue currently. I couldn't able to connect to redshift.

**Comment by argenisleon** [comment]
Hi @IshanDindorkar, @niteshnicholas 

We are releasing today version 2.2.6. You can check the progress here https://github.com/ironmussa/Optimus/pull/556#pullrequestreview-248220639

**Comment by argenisleon** [comment]
@IshanDindorkar @niteshnicholas 2.2.6 is out!

**Comment by IshanDindorkar** [comment]
Thank you @argenisleon for giving an update regarding new release. I will use the new released version of library going forward.
