### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by niteshnicholas** [ironmussa/Optimus#558]

**Comment by niteshnicholas** [comment]
While installing the latest optimuspyspark 2.5.51, I am getting error 
ERROR: h2o-pysparkling-2-4 2.4.10 has requirement pyspark<=2.4.0,>=2.4.0, but you'll have pyspark 2.4.1 which is incompatible.

Furthermore when I do run the following 
from optimus import Optimus   I get the error
ImportError: cannot import name 'abc'

**Comment by argenisleon** [comment]
Hi @niteshnicholas,
Thanks for the report. Now checking.

**Comment by argenisleon** [comment]
Hi @niteshnicholas ,

About 
```ERROR: h2o-pysparkling-2-4 2.4.10 has requirement pyspark<=2.4.0,>=2.4.0, but you'll have pyspark 2.4.1 which is incompatible.``` It seems some bug. The versions seem to be right. We open an issue in https://github.com/h2oai/sparkling-water/issues/1244
This not should not affect how optimus works.

About :
```
from optimus import Optimus I get the error
ImportError: cannot import name 'abc'
```

Please try:
```
pip uninstall bson
pip install pymongo
```
See this for reference:

https://github.com/py-bson/bson/issues/82

We are going to fix this in the next release.

**Comment by niteshnicholas** [comment]
Thanks argenisleon
