### ISSUE TITLE
[BUG] JDBC Redshift connection url. Port not configured.

### ISSUE THREAD

**Issue by niteshnicholas** [ironmussa/Optimus#562]
While creating the JDBC redshift connection Url, the port is not getting added in the Url.
Port is getting configured later but it is not getting added in the Url.

This gonna be my first contribution towards Open Source Community. Needed help in contribution and making PR if needed.

**Comment by argenisleon** [comment]
Hi @niteshnicholas,

Let me know if you need help with this.

**Comment by niteshnicholas** [comment]
I am adding the changes needed for redshift url in a branch. Needed help in writing test cases and coverage.

**Comment by niteshnicholas** [comment]
Created a PR with branch name redshift_url_port_added   from the grofers account. Let me know the changes needed or things more to do.

**Comment by argenisleon** [comment]
Hi @niteshnicholas ,

I already pull https://github.com/ironmussa/Optimus/pull/564 to master. I am working on tests here https://github.com/ironmussa/Optimus/tree/feature/improve_jdbc/tests/sql

I am creating docker containers for some popular databases to test. I have some problems using alchemy with redshift and mssql. Any help is welcome

**Comment by niteshnicholas** [comment]
I am closing this issue as it the fixed code is merged.
