### ISSUE TITLE
[Enhancement] Can we provide schema as an option for JDBC

### ISSUE THREAD

**Issue by niteshnicholas** [ironmussa/Optimus#563]
Currently in JDBC connection schema is set to default "public". Can we provide schema name as an option too.

**Comment by FavioVazquez** [comment]
@argenisleon can you take a look please? Maybe the issue with @niteshnicholas #562 is related.

**Comment by argenisleon** [comment]
Hi @niteshnicholas ,

Could you include this fix in the actual PR you are working? https://github.com/ironmussa/Optimus/pull/564

It seems that you need to include the param ```currentSchema``` int string conection 

```jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema```
