### ISSUE TITLE
Is there a way to disable caching of dataframe.

### ISSUE THREAD

**Issue by pallav1991** [ironmussa/Optimus#583]
I have a dataframe.
when i do

> kc.fingerprint_cluster(df, columnname)

then i change some values in daframe the above code is still returning the same data.
The same happens for profiler to.

is there a way that i set a property to disable caching and all the functions should stop there own caching of dataframe.

**Comment by argenisleon** [comment]
Hi @pallav1991,
Not at the moment. But think about it maybe it's better to let the user handle the cache and the repartitions operations.

At the moment you could to something like this.

```
kc.fingerprint_nocache = fingerprint_nocache

def fingerprint_nocahe(df, columns):
    """
    Create the fingerprint for a column
    :param df: Dataframe to be processed
    :param columns: Column to be processed
    :return:
    """

    def _split_sort_remove_join(value, args):
        """
        Helper function to split, remove duplicates, sort and join back together
        :param value:
        :param args:
        :return:
        """
        # Split into whitespace-separated token
        split_key = value.split()

        # Sort and remove duplicated items
        sorted(set(split_key))

        # join the tokens back together
        return "".join(split_key)

    columns = parse_columns(df, columns)
    for col_name in columns:
        output_col = col_name + "_FINGERPRINT"
        df = (df
              .withColumn(output_col, F.col(col_name))
              .cols.trim(output_col)
              .cols.lower(output_col)
              .cols.remove_special_chars(output_col)
              .cols.remove_accents(output_col)
              .cols.apply(output_col, _split_sort_remove_join, "string")
              )
    return df
```

I did not test the code but this should work

**Comment by pallav1991** [comment]
This works but i would like something in below lines because there are few more methods which i would like to disable the caching.

Optimus(disablefilter=true)

**Comment by argenisleon** [comment]
Hi @pallav1991,

Now when starting Optimus you can use ```Optimus(cache=False)``` to disable the cache.
Hope this help

**Comment by pallav1991** [comment]
thanks @argenisleon
