### ISSUE TITLE
Explore API standarization

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#585]
Profiler, Keycollision, Outliers. JDBC does not have a standard way to be used.

**Comment by eschizoid** [comment]
@argenisleon Can you elaborate a bit more about the work required here? Maybe I can help  :)

**Comment by argenisleon** [comment]
At the moment Novembre 2019 the API seems very stable. We think we can improve how users access the Key Collision , Distance Cluster and encoding functions.

For the profiler, JDBC and Outliers we have:

* Using Optimus object

**Profiler**
```
op.profiler.run()
```

**JDBC**
```
db = op.connect(
    driver="mysql",
    host="165.227.196.70", 
    database= "optimus", 
    user= "test", 
    password = "test")
```
* Using Dataframe object:

**Outliers**
```
df.outliers.tukey("age").select()
```

### What can be improved

**Key Collision and distance cluster and encoding**
The string_to_index and bucketizer functions are already exposed. I think we can improve how to access for example ```fingerprint_cluster``` 

At the moment the user needs:

```
from optimus.ml import keycollision as keyCol
df_kc = keyCol.fingerprint_cluster(df, 'STATE')
```
and could be written

```
df.ml.fingerprint_cluster('STATE')
```

@eschizoid What do you think?

**Comment by eschizoid** [comment]
@argenisleon It makes sense, but let me familiarize myself with these API's i can prepare a more elaborate answer :)

I would definitely be happy taking this ticket though...

**Comment by argenisleon** [comment]
All this has been refactored in 3.0.
