### ISSUE TITLE
Create docker compose file with db containers

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#600]
For testing purpose, we need to create a docker compose file to test the JDBC Class against multiple databases.

We need:

* Postgre
* Redshift
* MariaDB
* Mysql
* Oracle 
* Microsoft SQL Server

At the moment we have some docker commands here:https://github.com/ironmussa/Optimus/blob/master/tests/sql/readme.md

After the initialization, the databases need to be filed with dummy data. We have some work here https://github.com/ironmussa/Optimus/blob/master/tests/sql/sql.ipynb

**Comment by arpit1997** [comment]
Hey @argenisleon 
First time contributor here. Can I take up this issue?

Please correct me if I am wrong you are talking about this right? 
Converting individual commands mentioned in the `README.md` to convert to a `docker-compose.yml` file.

**Comment by argenisleon** [comment]
Hi @arpit1997,
I update the description. Hope this clarifies the issue.
Let me know if you need more info.

And yes you can take the issue :)

**Comment by argenisleon** [comment]
Hi @arpit1997,

Are you planning to work on this?

**Comment by arpit1997** [comment]
Hey got busy with some work. I will try to complete it by this weekend.

**Comment by arpit1997** [comment]
@argenisleon I am running into the following problem while connecting postgres using Optimus

*Code:*

```python
db =  op.connect(
    db_type="postgres",
    host=host,
    database= db_name,
    user= user,
    password = password,
    port=port)
```

It throws
 ```
Py4JJavaError: An error occurred while calling o118.load.
: java.sql.SQLException: No suitable driver
```

While running Optimus it shows that postgres odbc driver jar is provided

```
INFO:optimus:PYSPARK_SUBMIT_ARGS=--jars "file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/RedshiftJDBC42-1.2.16.1027.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/mysql-connector-java-8.0.16.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/ojdbc8.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/postgresql-42.2.5.jar" --driver-class-path "/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/RedshiftJDBC42-1.2.16.1027.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/mysql-connector-java-8.0.16.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/ojdbc8.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/postgresql-42.2.5.jar" --conf "spark.sql.catalogImplementation=hive" pyspark-shell
```

I can not find the issue, if you can provide me a solution or point me to right direction it would be great.

**Comment by argenisleon** [comment]
Hi @arpit1997 
Are you working in Windows, Linux or Mac?

**Comment by arpit1997** [comment]
I am working on Linux (Ubuntu 18.04)

**Comment by arpit1997** [comment]
@argenisleon Tried investigating the issue further and when I am trying to connect with postgres it is using following connection string `jdbc:postgres://127.0.0.1:5432/optimus?currentSchema=public` This connection string throws the error above. 

I made some changes and tried to use this `jdbc:postgresql://127.0.0.1:5432/optimus?currentSchema=public` connection string and it was working. But there is an issue with this. If there is a RedShift JDBC jar available then it tries to use that driver for connecting and fails. I removed the redshift JDBC driver to make it work. 

Details:

Postgres driver: `postgresql-42.2.5.jar`
Spark version: 2.4.3
Overall jars:
```
optimus:PYSPARK_SUBMIT_ARGS=--jars "file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/RedshiftJDBC42-1.2.16.1027.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/mysql-connector-java-8.0.16.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/ojdbc8.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/postgresql-42.2.5.jar" --driver-class-path "/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/RedshiftJDBC42-1.2.16.1027.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/mysql-connector-java-8.0.16.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/ojdbc8.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/postgresql-42.2.5.jar" --conf "spark.sql.catalogImplementation=hive" pyspark-shell
```
Standalone spark cluster on Ubuntu 18.04


@argenisleon Can you confirm if this looks like a configuration issue/version mismatch or a bug. I can provide more details if required.

**Comment by argenisleon** [comment]
@arpit1997 maybe is related to this. https://stackoverflow.com/questions/31951518/redshift-and-postgres-jdbc-driver-both-intercept-jdbc-postgresql-connection-st

Can you try to connect to Postgres with both driver present an the OpenSourceSubProtocolOverrid param ```jdbc:postgresql://localhost:5432/postgres?OpenSourceSubProtocolOverride=true``` and see what what happend?

**Comment by arpit1997** [comment]
@argenisleon The solution works. It takes the postgres driver when provided `OpenSourceSubProtocolOverride` param. But as mentioned above the first problem still pertains. Optimus uses `jdbc:postgres://127.0.0.1:5432/optimus?currentSchema=public` connection string for postgres which throws `no suitable driver found` error but works fine with `jdbc:postgresql://127.0.0.1:5432/optimus?currentSchema=public`

**Comment by argenisleon** [comment]
Yes, please.
