### ISSUE TITLE
Can not connect to postgres - No suitable driver found

### ISSUE THREAD

**Issue by arpit1997** [ironmussa/Optimus#616]
I am running into the following problem while connecting postgres using Optimus

*Code:*

```python
db =  op.connect(
    db_type="postgres",
    host=host,
    database= db_name,
    user= user,
    password = password,
    port=port)
```

It throws
 ```
Py4JJavaError: An error occurred while calling o118.load.
: java.sql.SQLException: No suitable driver
```

While running Optimus it shows that postgres odbc driver jar is provided

```
INFO:optimus:PYSPARK_SUBMIT_ARGS=--jars "file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/RedshiftJDBC42-1.2.16.1027.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/mysql-connector-java-8.0.16.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/ojdbc8.jar,file:///home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/postgresql-42.2.5.jar" --driver-class-path "/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/RedshiftJDBC42-1.2.16.1027.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/mysql-connector-java-8.0.16.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/ojdbc8.jar:/home/arpit/.virtualenvs/optimus-prime/lib/python3.6/site-packages/optimuspyspark-2.2.9-py3.6.egg/optimus/jars/postgresql-42.2.5.jar" --conf "spark.sql.catalogImplementation=hive" pyspark-shell
```

Tried investigating the issue further and when I am trying to connect with postgres it is using following connection string `jdbc:postgres://127.0.0.1:5432/optimus?currentSchema=public` This connection string throws the error above. 

I made some changes and tried to use this `jdbc:postgresql://127.0.0.1:5432/optimus?currentSchema=public` connection string and it was working. But there is an issue with this. If there is a RedShift JDBC jar available then it tries to use that driver for connecting and fails. I removed the redshift JDBC driver to make it work. 

Details:

Postgres driver: `postgresql-42.2.5.jar`
Spark version: 2.4.3
Standalone spark cluster on Ubuntu 18.04

As for the redshift and postgres driver overlap, solution suggested by @argenisleon https://stackoverflow.com/questions/31951518/redshift-and-postgres-jdbc-driver-both-intercept-jdbc-postgresql-connection-st works.

**Comment by arpit1997** [comment]
@argenisleon I can submit a PR for both the issues
1. Overlap between redshift and postgres drivers
2. No suitable driver found error when connecting to postgres. Connection string should be `jdbc:postgresql` instead of `jdbc:postgres`

**Comment by argenisleon** [comment]
Hi @arpit1997,
Please go ahead with the pull request

**Comment by argenisleon** [comment]
Thanks for this. Now in master.
