### ISSUE TITLE
Python 3 No module named '_ssl'  when pip install optimuspyspark into python package

### ISSUE THREAD

**Issue by RayTsui** [ironmussa/Optimus#639]
I install python3.7.3 via downloading python source code and compiling, configure, and finally make && make install, then 'pip install -t $HOME/tmp/python3.7.3/lib/python3.7/site-packages optimuspyspark '. After that, I verify if the usage is successful, I enter into python REPL, and enter 'from optimus.helpers.decorators import *', it gives me 
"
python3.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'
"
However, I have tried all ways I can find online, no one is workable. Is there any way to workaround it. Thanks so much for your suggestion.

**Comment by argenisleon** [comment]
Hi @RayTsui ,

Did you try this https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl.

Seems to be related with compiling python with the SSL module. 

If you already tried this can you let us know what have you tried?

**Comment by RayTsui** [comment]
Hi @argenisleon, I think optimuspyspark may have a limitation that io module in optimuspyspark depends on ssl, ssl depends on _ssl module. If ones are going to install optimuspyspark via pip into a compiled python package, and distributed this compiled python package to spark cluster, actually, save func in io cannot make it because of lack of _ssl module. And most of time, you can not manage worker node in spark cluster and even cannot manually install openssl, so optimuspyspark can not be used.

In addition, the link you give me is for python 2.7, and --with-ssl option is not available for python 3.6+

**Comment by argenisleon** [comment]
@RayTsui can you isolate the problem? I can not figure out where SSL is used.

**Comment by argenisleon** [comment]
@RayTsui it seems that pymongo use SSL https://github.com/mongodb/mongo-python-driver/search?q=ssl&unscoped_q=ssl. It is possible for you to test Optimus removing pymongo and test if it works?
