### ISSUE TITLE
Profiler fails when datetime or numeric types are detected

### ISSUE THREAD

**Issue by arpit1997** [ironmussa/Optimus#641]
When running the profiler with `infer=True` with actual columns having datetime and integer types it fails with traceback attached.

I am attaching a file which I experimented with.
[crimes-in-boston.zip](https://github.com/ironmussa/Optimus/files/3538623/crimes-in-boston.zip)

```python
from optimus import Optimus
op = Optimus()
df2 = op.read.csv('crime.csv')
op.profiler.run(df2, '*', infer=True)
```

Traceback:

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-5-e4a0041fc71c> in <module>
----> 1 op.profiler.run(df2, '*', infer=True)

~/Projects/Optimus/optimus/helpers/decorators.py in timed(*args, **kw)
     26     def timed(*args, **kw):
     27         start_time = timeit.default_timer()
---> 28         f = method(*args, **kw)
     29         _time = round(timeit.default_timer() - start_time, 2)
     30         logger.print("{name}() executed in {time} sec".format(name=method.__name__, time=_time))

~/Projects/Optimus/optimus/profiler/profiler.py in run(self, df, columns, buckets, infer, relative_error, approx_count)
    199 
    200                 if col["column_dtype"] == "date":
--> 201                     hist_year = plot_hist({col_name: hist_dict["years"]}, "base64", "years")
    202                     hist_month = plot_hist({col_name: hist_dict["months"]}, "base64", "months")
    203                     hist_weekday = plot_hist({col_name: hist_dict["weekdays"]}, "base64", "weekdays")

TypeError: list indices must be integers or slices, not str
```

I believe the error at https://github.com/ironmussa/Optimus/blob/master/optimus/helpers/columns_expression.py#L93, It always goes to string datatype if statement. function `is_column_a` takes df, column_name and dtypes as args. df have all types as string and it matches with string only. 
@argenisleon Correct me if I am wrong.

**Comment by argenisleon** [comment]
@arpit1997 you are right. The data inference process is done after the general starts are calculated. The hist needs to know the data type to correctly calculate the hist. 

I will push a fix tomorrow. 

Thanks for the report.

**Comment by arpit1997** [comment]
@argenisleon Any update on this?

**Comment by argenisleon** [comment]
@arpit1997 This is now in master and available in a new release

**Comment by arpit1997** [comment]
Thank you. I can now start with #632
