### ISSUE TITLE
urllib.error.URLError: <urlopen error unknown url type: ['hdfs']

### ISSUE THREAD

**Issue by pallav1991** [ironmussa/Optimus#642]
when i provide the HDFS url while reading a parquet file in HDFS in remote system. I am getting above exception. I have was able to resolve this on my local system when i remove hdfs from #helper/check.py file in is_URL method.

**Comment by argenisleon** [comment]
Hi @pallav1991 
Is it possible to you to push a fix for this?

**Comment by pallav1991** [comment]
I have no fix for this the only thong i did was 
optimus/helpers/check.py #is_url methord to accepts HDFS.
and changed the host of my HDFS to work as host name. because even if i did above chnages the urllib which you have used is not accepting HDFS when ip address used in the url. if the hostname is used then it is working.


for example:
hdfs://10.171.0.111:9000/dev/abc.parquet ////does not work

hdfs://hostname:9000/dev/abc.parquet  ////work's

**Comment by argenisleon** [comment]
Thanks @pallav1991 
Now we have an HDFS node to make some tests.
Pushing a fix soon.
