### ISSUE TITLE
Adding function to handle cols and dataframes metadata

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#644]

**Comment by arpit1997** [comment]
@argenisleon can you provide more info on this? If you are not working on this then I can take this up for the weekend.

**Comment by argenisleon** [comment]
Hi @argenisleon 
Is's already done https://github.com/ironmussa/Optimus/blob/develop/optimus/dataframe/extension.py#L490

I expect to merge to master tomorrow.
