### ISSUE TITLE
Explore Pandas, Dask and Rapids as Optimus backends

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Optimus#660]
Integrating rapids https://rapids.ai/ into Optimus can give and amazing boots speed, most of all in the data profiling area.

We want that Optimus as a high-level API in which the user can change the engine(Spark, rapids) without worry change in the code.

Spark can be very slow when handling some megabytes of data but shine for petabytes and seems to have better enterprise support.

A possible scenario can be to use rapids for realtime profiling to have feedback and then send jobs to spark clusters to process all the data. In a near the future maybe all the stack could be handle in rapids/dash.

After some exploration, I think we need to be sure that we can create histograms and top-N frequencies in a way that can scale.  Others transformations and aggregation seems to be easily replicable in rapids

I also explore how we pypika to create SQL query and run them over spark SQL or BlazingSQL. This seems to be the way to go to handle aggregations but seems inefficient for frequency and histograms against Spark RDD

**Comment by argenisleon** [comment]
Taking to @arpit1997 we think that pandas can be a good start to make Optimus pluggable with multiple backends. Also, pandas can be faster for some small data scenarios. 

So at the code level, I think there is some main point we can work: 

**The profiler**

The profiler has 3 main operations Aggregations, histograms, and frequencies.

Aggregations are created in ```create_expr() ```https://github.com/ironmussa/Optimus/blob/master/optimus/dataframe/columns.py#L493. I already make some work trying to create aggregation using SQL instead of Column expression. We could make some work in this function to use the panada approach:

```
data.agg(
    {
        # find the min, max, and sum of the duration column
        'duration': [min, max, sum],
         # find the number of network type entries
        'network_type': "count",
        # min, first, and number of unique dates per group
        'date': [min, 'first', 'nunique']
    }
)
```
To calculate multiple aggregations in one pass.

Histograms and frequencies seem to be more straight forward. Although we need to start implementing columns and rows operations for every kind of dataframe (pandas, dask. rapids)

**Sessions**
Spark is tightly coupled to the Optimus constructor. A good approach can be something like creating a session and pass it to Optimus. For example:
```
from optimus import Optimus
# This could be a OptmiusPandasSession, dask or rapids session
session = OptimusSparkSession(actual_optimus_constructor_params)

op = Optimus(session)
```

Actually Opimus() also load all the jars files to handle the database connections. This must be considered when implementing other backends.

@arpit1997 because you are taking the lead here please let me know how we organize the work and how I can help.

**Comment by arpit1997** [comment]
Here is what I am currently at.

We have the following modules

DataFrame - Monkey patched Spark Dataframe with additional functions. 
The problem: The additional functions executes functions from pyspark. We need an Interface mechanism like DataFrameInterface and Implementations like SparkDataFrame, PandasDataFrame, DaskDataFrame.

Profiler - calculates stats using DataFrame functions defined in the Dataframe module. If DataFrame module get patched to support multiple backends then this should require major change

IO - Reader/Writer module for JDBC and other stores.
Also a wrapper around Spark and works with Spark only. It requires major change. Basically we need interfaces like JDBCIO and Implementations SparkJDBCIO, PandasJDBCIO, DaskJDBCIO etc.

ml/dl - Calls Spark's functions under the hood and some utility functions from Optimus

outliers - Calls Spark's functions under the hood and some utility functions from Optimus

Optimus class: Completely tied to Spark right now. We need again Interface for this as pointed above by @argenisleon. 

I am thinking first version to target only DataFrame and Optimus module, to make a smallest working example of pluggable backends. Based on how this goes I will move to profiler, io and ml/dl. First backend will be pandas to be supported this way

**Comment by argenisleon** [comment]
After working some hours with Dask, most of the work here is going to be in creating what I am going to call "the aggregation layer". 

And essential work in Optimus is about how much we parallelize operations. We need to write a layer so the internal components can play nicely and backend independent. This layer is going to be used mainly in profiling operations.

Also implementing a pandas interface does not have much sense because Dask has a similar API and we can gain much in performance using it.

I am going to start a project to better organize the next steps.
