### ISSUE TITLE
Add geospatial features to optimus

### ISSUE THREAD

**Issue by kaushikCanada** [ironmussa/Optimus#663]
can we have geopandas like features in optimus?

**Comment by arpit1997** [comment]
@kaushikCanada So currently we are looking at how we can plug different backends like pandas dask maybe geopandas also. Have you looked at [geospark](https://github.com/DataSystemsLab/GeoSpark) this might just solve the problem you are having

**Comment by kaushikCanada** [comment]
Thank you for your reply. I have looked at lots of packages as i am working
on property visualosation pipelines. Geospark does not have good apis and
is not being used anywhere in production. If optimus could inclide this
feature it would be great for the geo bi world.
Thanks,
Roy

**Comment by arpit1997** [comment]
@kaushikCanada Neither me nor @argenisleon have much experience with GeoSpatial data wrangling. One problem which I see that its not available in Python. Can you please elaborate on how GeoSpark has bad APIs? It will help us in determining what we should implement.

@argenisleon Any thoughts on this?

**Comment by kaushikCanada** [comment]
Okay I will expand a little. I have like 10 million polygons on which i can
potentially be doing self joins and other geospatial joins as per ogc. Now
python has very good wrappers in the form of GeoPandas, Shapely, Fiona, and
gdal. The other way to do this is to go the spatial database way such as
spatialite, postgis, H2gis, etc.. I have tried all of these and only
postgis matches close to a usable solution, but does not have embedded
solutions(which is preferable for microservices). next i came up on spark
solutions and there are several i tried, including spatialspark, hadoopgis,
locationspark, and finally last but not the least geospark. WHile the
others have their own caveats, geospark is the latest one and being a lover
of spark i was really expecting good support and tooling around it.
However, it turns out there are a couple of things missing prima face.
The pyspark support seems to be bad to nonexistent. Although spatial sql is
supported, it needs to be specially included into the project. Also, there
are serious serialization issues as geospark uses its custom serializer.
all in all i found it quite difficult for average analysts to work with
geospark.
an ideal library should have parallelizable geospatial join capabilities
along with OGC sql facilites. Geopandas is good except for two things - no
parallelization and no sql. i think both these capabilites can be improved
upon optimus.

**Comment by argenisleon** [comment]
Hi @kaushikCanada 
Support Geospatial operation sounds interesting. In a past project, I rellied on mongo to make some geospatial operation around points and polygons.

Maybe we could start thinking Geospatial features. @kaushikCanada could give a detailed example of the first feature you will incorporate to Optimus?

**Comment by kaushikCanada** [comment]
Yes location intelligence is really becoming golden now that we are more
globalized, and everyone wants to do spatial autocorrelation and stuff..
however, the basic unit for this is incorporating wither geopandas directly
or shapely library into optimus.. Me? I am just a data engineer, lol i have
done a lot fo programs past 10 years but never been a committer. if there
is noone else then i could give it a try. The first thing to do is to make
sure optimus understands types like polygon, point , multipolygon etc..
please do share any ideas that could help in this.

**Comment by argenisleon** [comment]
I am putting this here for reference https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/137058993011870/882779309834027/6891974485343070/latest.html

https://github.com/harsha2010/magellan

As @kaushikCanada said building a polygon, point, multipolygon object could be a good start. @kaushikCanada are you able to contribute some code here?

**Comment by kaushikCanada** [comment]
This library is quite old. I am more interested with data than i am at
programming. I was trying out the abstract udf and have some questions.
Does it use the pandas arrow decorator underneath? And how do i
differentiate between grouped map and grouped aggregates. How do i do a
function like json.loads on a column?

I could test if megallan works for optimus.

Thanks,
Roy

**Comment by argenisleon** [comment]
Yes, it uses pandas arrow decorator underneath. At the moment only scalar UDF is implemented , although you can use pandas_udf decorators with Optimus the same way that you would use ti with Spark.  

Could you explain further the json.loads on a column question?
