### ISSUE TITLE
Refactor IO package 

### ISSUE THREAD

**Issue by eschizoid** [ironmussa/Optimus#709]
@argenisleon This is still WIP, but I would like to get some initials thoughts and see if you like the idea and could be merged down when is ready.

https://github.com/eschizoid/Optimus/pull/3

Feel free to close the ticket if you don't see that much value :)

**Comment by eschizoid** [comment]
@argenisleon Thanks for taking the time and reviewing the repo.

Based on the comments you left, it seems that you are on board with the idea. I will continue with the effort and hopefully i can get the PR in a good shape this weekend :)

**Comment by argenisleon** [comment]
@eschizoid Yes, it looks amazing :)

**Comment by argenisleon** [comment]
Hi @eschizoid any news on this?

**Comment by eschizoid** [comment]
#727 sitll WIP, will start adding test this weekend
