### ISSUE TITLE
levenshtein_cluster change Name

### ISSUE THREAD

**Issue by pallav1991** [ironmussa/Optimus#716]
please change ml/distancecluster.py line number line number 114 in method levenstine_cluster 

from 
`.cols.drop([input_col + "_FROM", input_col + "_TO", input_col + "_LEVENSHTEIN_DISTANCE"])`
TO
`.cols.drop([input_col + "_FROM", input_col + "_TO", input_col + "***LEVENSHTEIN_DISTANCE"])`

**Comment by pallav1991** [comment]
-1

**Comment by FavioVazquez** [comment]
Caan you give more context here @pallav1991 ?

**Comment by argenisleon** [comment]
@FavioVazquez @pallav1991 I got this! Fixed in the comming release

**Comment by argenisleon** [comment]
Fixed #708
