### ISSUE TITLE
Using PEP-8 style guide for naming conventions

### ISSUE THREAD

**Issue by afaq404alam** [ironmussa/Optimus#72]
I was going through the code and found that various methods and variables have been named using camel casing. Also few methods starting with "__" double underscores. We should just use one "_" underscore to differentiate internal methods from public methods. I think it would be a good idea to start by using PEP-8 naming conventions for modules, function, methods and variables. Please let me know your thoughts on this.

**Comment by FavioVazquez** [comment]
Hi @afaq404alam! Thanks for the interest. I think you are right actually. Are you willing to create a PR with these changes?

**Comment by afaq404alam** [comment]
Yeah, sure. I would be happy to take this up.

**Comment by FavioVazquez** [comment]
Thank you @afaq404alam! We'll be waiting.
