### ISSUE TITLE
Outliers module not working

### ISSUE THREAD

**Issue by cemsa1992** [ironmussa/Optimus#760]
I have tried to chain or import outliers with many different methods. I have tried importing tukey directly as well. Everything results in  error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-99-91314833f34f> in <module>
----> 1 outliers = df_csv.outliers.tukey("cnt").select().table()

C:\Spark\spark-3.0.0-preview-bin-hadoop2.7\python\pyspark\sql\dataframe.py in __getattr__(self, name)
   1300         if name not in self.columns:
   1301             raise AttributeError(
-> 1302                 "'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
   1303         jc = self._jdf.apply(name)
   1304         return Column(jc)

AttributeError: 'DataFrame' object has no attribute 'outliers'
`

**Comment by argenisleon** [comment]
Hi @cemsa1992 ,

Thanks for the report. I am going to push a fix in a couple of hours.

**Comment by argenisleon** [comment]
@cemsa1992,
I am pushing 2.2.29 to pip. It'll be available in the next hour.

**Comment by argenisleon** [comment]
@cemsa1992 2.2.29 is now available. Please let me know if this fix the problem.

**Comment by cemsa1992** [comment]
> @cemsa1992 2.2.29 is now available. Please let me know if this fix the problem.

It is fixed indeed. Thanks! I recently found this library and it is outstanding!
