### ISSUE TITLE
[Question]: dependencies of Optimus

### ISSUE THREAD

**Issue by dclong** [ironmussa/Optimus#844]
I noticed that Optimus have specific single version dependencies instead of dependencies with a range of versions. This makes it hard to install Optimus along with other libraries sometimes. May I ask why Optimus has so tight restrictions on dependencies?

**Comment by argenisleon** [comment]
Hi @dclong 
Not a specific reason for this. Could you PR some improvements?

**Comment by dclong** [comment]
@argenisleon Sure. I'd be happy to do that.

**Comment by argenisleon** [comment]
Hi @dclong, Are you willing to work on this? :)

**Comment by dclong** [comment]
@argenisleon Yes, I'm very willing to work on it. Sorry that I was busy the past day. I will try to have a PR this week.

**Comment by dclong** [comment]
@argenisleon I'm so sorry about the delay! I final got some time over the weekend to work on the issue. 

As the first step of relaxing versions restrictions of dependencies, I'm cautious and only relax on minor versions generally speaking. However, I found that TensorFlow 1 is used as dependency. Do you think we can use TensorFlow 2 instead since it is a significant improvement over TF1.

**Comment by argenisleon** [comment]
Yes let's update to 2.0 and run the test to see what happens :)

**Comment by argenisleon** [comment]
We are going to remove pip support for 3.0
