### ISSUE TITLE
Directory Not Empty: linalg Error

### ISSUE THREAD

**Issue by avinish1** [ironmussa/Optimus#880]
**While trying to install, Initially faced a "pypandoc" error which I was able to resolve installing "pypandoc" seperately but after that I face this error**

**" ERROR : Could not install packages due to an enviroment error : [ERROR 39] Directory not empty : linalg "**

**Laptop (please complete the following information):**
 - Windows 10 Pro
 - chrome

**Comment by argenisleon** [comment]
Hi @avinish1,

Could you please try to install Optimus in a conda environment?

**Comment by argenisleon** [comment]
@avinish1 Closing this. Let me know if I could help with the issue.
