### ISSUE TITLE
Issue in opening file in PySpark shell

### ISSUE THREAD

**Issue by SaiAle501** [ironmussa/Optimus#941]
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: java.lang.IllegalArgumentException: Unsupported class file major version 58

**Comment by argenisleon** [comment]
Hi @SaiAle501,
 I think this is a problem with the java version. Maybe your current pyspark version needs java 8.

See https://stackoverflow.com/questions/53583199/pyspark-error-unsupported-class-file-major-version

**Comment by argenisleon** [comment]
@SaiAle501 Did this solved the issue?
